basePath: /api
consumes:
- application/json
definitions:
  ConfigContactsSt:
    properties:
      email:
        type: string
        x-go-name: Email
      phone:
        type: string
        x-go-name: Phone
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
  ConfigSt:
    properties:
      contacts:
        $ref: '#/definitions/ConfigContactsSt'
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
  DicSt:
    properties:
      config:
        $ref: '#/definitions/ConfigSt'
      usr_types:
        items:
          $ref: '#/definitions/UsrTypeSt'
        type: array
        x-go-name: UsrTypes
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
  UsrTypeSt:
    properties:
      id:
        format: int64
        type: integer
        x-go-name: Id
      name:
        type: string
        x-go-name: Name
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
host: gms_temp.kz
info:
  description: |-
    <br/>
    В каждом авторизованном запросе необходимо указать http-заголовок:
    ```
    Authorization: token
    ```
    token можно получить:
    + в ответе авторизации (/profile/auth)
    + в ответе регистрации (/profile/reg)
    <br/>
    ### Константы
    ```
    AppUrl     = "https://gms_temp.kz"

    UsrTypeUndefined = 0
    UsrTypeAdmin = 1
    ```
    <br/>
    ### Работа с файлами
    Файлы(фотки) из АПИ приходят в виде __path__. Чтобы отобразить ее на экране надо добавить префикс: https://gms_temp.kz/api/fs/__path__. Что бы залить фото на сервер надо использовать АПИ `/fs/`, подробно можно посмотреть ниже по документации.

    Для большинства картин, которые возвращает API, действуют следующие параметры(query):
    ```
    .../photo.jpg?w=200&h=200&m=fit|fill
    ```
    Где:
    + w - желаемая ширина картинки
    + h - желаемая высота картинки
    + m - метод изменения размера. Допустимые значения:
    fit - картина полностью поместится в область (сохраняя соотношение)
    fill - картина может обрезаться, но покроет всю область
    <br/>
    ### Websocket
    websocket доступен по адресу `wss://gms_temp.kz/api/websocket?auth_token=<token>`. По вебсокету приходят такие же данные как и в пушах.
  title: GmsTemp API.
  version: 1.0.0
paths:
  /dic:
    get:
      operationId: get_dic
      parameters:
      - description: |-
          Хэш сумма значении ответа. Используется для сверки версии ответа от сервера.
          В первый раз нужно передать пустую строку, потом нужно передать то что вернул сервер в ответе.
        in: query
        name: hs
        type: string
        x-go-name: Hs
      responses:
        "200":
          $ref: '#/responses/dicRep'
      summary: Все справочники.
      tags:
      - dic
produces:
- application/json
responses:
  dicRep:
    description: '`data` - может быть null, если __hs__ переданный в запросе совпадает
      с серверным __hs__, в этом случае фронт должен использовать предыдущее значение
      ответа от сервера'
    schema:
      properties:
        data:
          $ref: '#/definitions/DicSt'
        hs:
          type: string
          x-go-name: Hs
      type: object
schemes:
- https
- http
swagger: "2.0"
