basePath: /
consumes:
- application/json
definitions:
  ConfigContactsSt:
    properties:
      email:
        type: string
        x-go-name: Email
      phone:
        type: string
        x-go-name: Phone
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
  ConfigSt:
    properties:
      contacts:
        $ref: '#/definitions/ConfigContactsSt'
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
  DicDataSt:
    properties:
      config:
        $ref: '#/definitions/ConfigSt'
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
  ErrRepSt:
    properties:
      error_code:
        description: Код ошибки
        type: string
        x-go-name: ErrorCode
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/adapters/httpapi/rest
host: api.gms_temp.com
info:
  description: |-
    <br/><details>
    <summary>**Константы**</summary>
    ```
    # Roles
    RoleGuest = "guest"
    RoleAdmin = "admin"
    ```
    </details>
  title: GmsTemp API.
  version: 1.0.0
paths:
  /config:
    put:
      description: 'Allowed to: `UsrTypeAdmin`'
      operationId: hConfigUpdate
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/ConfigSt'
      responses:
        "200":
          description: ""
        "400":
          $ref: '#/responses/errRep'
      security:
      - token: []
      summary: Конфикурационные данные системы.
      tags:
      - config
  /dic:
    get:
      description: Это АПИ нужно вызывать при каждом запуске приложения (фронта)
      operationId: hDicGet
      parameters:
      - description: |-
          Хэш сумма значении ответа. Используется для сверки версии ответа от сервера.
          В первый раз нужно передать пустую строку, потом нужно передать то что вернул сервер в ответе.
        in: query
        name: hs
        type: string
        x-go-name: Hs
      responses:
        "200":
          $ref: '#/responses/dicRep'
        "400":
          $ref: '#/responses/errRep'
      summary: Все справочники.
      tags:
      - dic
produces:
- application/json
responses:
  dicRep:
    description: |-
      `hs` - фронту нужно сохранить значение этого поля и передать в параметре следующего запроса
      <br/>`data` - может быть null, если __hs__ переданный в запросе совпадает с серверным __hs__, в этом случае фронт должен использовать предыдущее значение ответа от сервера
    schema:
      properties:
        data:
          $ref: '#/definitions/DicDataSt'
        hs:
          type: string
          x-go-name: Hs
      type: object
  errRep:
    description: ""
    schema:
      $ref: '#/definitions/ErrRepSt'
schemes:
- https
- http
securityDefinitions:
  token:
    description: 'Пример: `Authorization: Bearer 2cf24dba5fb0a30e26e83b2`'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
