basePath: /api
consumes:
- application/json
definitions:
  ConfigContactsSt:
    properties:
      email:
        type: string
        x-go-name: Email
      phone:
        type: string
        x-go-name: Phone
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
  ConfigSt:
    properties:
      contacts:
        $ref: '#/definitions/ConfigContactsSt'
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
  DicDataSt:
    properties:
      config:
        $ref: '#/definitions/ConfigSt'
      usr_types:
        items:
          $ref: '#/definitions/UsrTypeSt'
        type: array
        x-go-name: UsrTypes
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
  ErrRepSt:
    properties:
      error_code:
        type: string
        x-go-name: ErrorCode
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/adapters/httpapi/rest
  UsrTypeSt:
    properties:
      id:
        format: int64
        type: integer
        x-go-name: Id
      name:
        type: string
        x-go-name: Name
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
host: gms_temp.kz
info:
  description: |-
    <br/><details>
    <summary>**Константы**</summary>
    ```
    AppUrl = "https://gms_temp.kz"

    UsrTypeUndefined = 0
    UsrTypeAdmin = 1
    ```
    </details>

    <details>
    <summary>**Работа с фото и файлами**</summary>

    Файлы(фотки) из АПИ приходят в виде __path__. Чтобы отобразить ее на экране надо добавить префикс: https://gms_temp.kz/api/fs/__path__.
    Что бы залить фото на сервер надо использовать АПИ `/fs/`, подробно можно посмотреть ниже по документации.

    Для большинства картин, которые возвращает API, действуют следующие параметры(query):
    ```
    .../photo.jpg?w=200&h=200&m=fit|fill
    ```
    Где:
    <ul>
    <li>w - желаемая ширина картинки</li>
    <li>h - желаемая высота картинки</li>
    <li>
    m - метод изменения размера. Допустимые значения:
    <ul>
    <li>fit - картина полностью поместится в область (сохраняя соотношение)</li>
    <li>fill - картина может обрезаться, но покроет всю область</li>
    </ul>
    </li>
    </ul>
    </details>

    <details>
    <summary>**Websocket**</summary>

    websocket доступен по адресу `wss://gms_temp.kz/api/websocket?auth_token=<token>`. По вебсокету приходят такие же данные как и в пушах.
    </details>
  title: GmsTemp API.
  version: 1.0.0
paths:
  /dic:
    get:
      description: asdfasdfasd fasdf asdf asd
      operationId: dic_get
      parameters:
      - description: |-
          Хэш сумма значении ответа. Используется для сверки версии ответа от сервера.
          В первый раз нужно передать пустую строку, потом нужно передать то что вернул сервер в ответе.
        in: query
        name: hs
        type: string
        x-go-name: Hs
      responses:
        "200":
          $ref: '#/responses/dicRep'
        "400":
          $ref: '#/responses/error_reply'
      summary: Все справочники.
      tags:
      - dic
produces:
- application/json
responses:
  dicRep:
    description: '`data` - может быть null, если __hs__ переданный в запросе совпадает
      с серверным __hs__, в этом случае фронт должен использовать предыдущее значение
      ответа от сервера'
    schema:
      properties:
        data:
          $ref: '#/definitions/DicDataSt'
        hs:
          type: string
          x-go-name: Hs
      type: object
  error_reply:
    description: ""
    schema:
      $ref: '#/definitions/ErrRepSt'
schemes:
- https
- http
securityDefinitions:
  token:
    description: 'Пример: `Authorization: 2cf24dba5fb0a30e26e83b2`'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
