basePath: /api
consumes:
- application/json
definitions:
  ConfigContactsSt:
    properties:
      email:
        type: string
        x-go-name: Email
      phone:
        type: string
        x-go-name: Phone
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
  ConfigSt:
    properties:
      contacts:
        $ref: '#/definitions/ConfigContactsSt'
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
  DicDataSt:
    properties:
      config:
        $ref: '#/definitions/ConfigSt'
      usr_types:
        items:
          $ref: '#/definitions/UsrTypeSt'
        type: array
        x-go-name: UsrTypes
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
  ErrRepSt:
    properties:
      error_code:
        description: Код ошибки
        type: string
        x-go-name: ErrorCode
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/adapters/httpapi/rest
  PhoneAndSmsCodeSt:
    properties:
      phone:
        type: string
        x-go-name: Phone
      sms_code:
        format: int64
        type: integer
        x-go-name: SmsCode
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
  UsrCUSt:
    properties:
      ava:
        type: string
        x-go-name: Ava
      name:
        type: string
        x-go-name: Name
      phone:
        type: string
        x-go-name: Phone
      type_id:
        format: int64
        type: integer
        x-go-name: TypeId
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
  UsrListSt:
    properties:
      ava:
        type: string
        x-go-name: Ava
      created_at:
        format: date-time
        type: string
        x-go-name: CreatedAt
      id:
        format: int64
        type: integer
        x-go-name: Id
      name:
        type: string
        x-go-name: Name
      phone:
        type: string
        x-go-name: Phone
      type_id:
        format: int64
        type: integer
        x-go-name: TypeId
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
  UsrNumbersSt:
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
  UsrProfileSt:
    properties:
      ava:
        type: string
        x-go-name: Ava
      created_at:
        format: date-time
        type: string
        x-go-name: CreatedAt
      id:
        format: int64
        type: integer
        x-go-name: Id
      name:
        type: string
        x-go-name: Name
      phone:
        type: string
        x-go-name: Phone
      type_id:
        format: int64
        type: integer
        x-go-name: TypeId
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
  UsrRegReqSt:
    properties:
      ava:
        type: string
        x-go-name: Ava
      name:
        type: string
        x-go-name: Name
      phone:
        type: string
        x-go-name: Phone
      sms_code:
        format: int64
        type: integer
        x-go-name: SmsCode
      type_id:
        format: int64
        type: integer
        x-go-name: TypeId
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
  UsrSt:
    properties:
      ava:
        type: string
        x-go-name: Ava
      created_at:
        format: date-time
        type: string
        x-go-name: CreatedAt
      id:
        format: int64
        type: integer
        x-go-name: Id
      name:
        type: string
        x-go-name: Name
      phone:
        type: string
        x-go-name: Phone
      type_id:
        format: int64
        type: integer
        x-go-name: TypeId
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
  UsrTypeSt:
    properties:
      id:
        format: int64
        type: integer
        x-go-name: Id
      name:
        type: string
        x-go-name: Name
    type: object
    x-go-package: github.com/rendau/gms_temp/internal/domain/entities
host: gms_temp.com
info:
  description: |-
    <br/><details>
    <summary>**Константы**</summary>
    ```
    AppUrl = "https://gms_temp.com"

    UsrTypeUndefined = 0
    UsrTypeAdmin = 1
    ```
    </details>

    <details>
    <summary>**Работа с фото и файлами**</summary>

    Файлы(фотки) из АПИ приходят в виде __path__. Чтобы отобразить ее на экране надо добавить префикс: https://gms_temp.com/api/fs/__path__.
    Что бы залить фото на сервер надо использовать АПИ `/fs/`, подробно можно посмотреть ниже по документации.

    Для большинства картин, которые возвращает API, действуют следующие параметры(query):
    ```
    .../photo.jpg?w=200&h=200&m=fit|fill
    ```
    Где:
    <ul>
    <li>w - желаемая ширина картинки</li>
    <li>h - желаемая высота картинки</li>
    <li>
    m - метод изменения размера. Допустимые значения:
    <ul>
    <li>fit - картина полностью поместится в область (сохраняя соотношение)</li>
    <li>fill - картина может обрезаться, но покроет всю область</li>
    </ul>
    </li>
    </ul>
    </details>

    <details>
    <summary>**Websocket**</summary>

    websocket доступен по адресу `wss://gms_temp.com/api/websocket?auth_token=<token>`. По вебсокету приходят такие же данные как и в пушах.
    </details>
  title: GmsTemp API.
  version: 1.0.0
paths:
  /config:
    put:
      description: 'Allowed to: `UsrTypeAdmin`'
      operationId: hConfigUpdate
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/ConfigSt'
      responses:
        "200":
          description: ""
        "400":
          $ref: '#/responses/errRep'
      security:
      - token: []
      tags:
      - config
  /dic:
    get:
      description: Это АПИ нужно вызывать при каждом запуске приложения (фронта)
      operationId: hDicGet
      parameters:
      - description: |-
          Хэш сумма значении ответа. Используется для сверки версии ответа от сервера.
          В первый раз нужно передать пустую строку, потом нужно передать то что вернул сервер в ответе.
        in: query
        name: hs
        type: string
        x-go-name: Hs
      responses:
        "200":
          $ref: '#/responses/dicRep'
        "400":
          $ref: '#/responses/errRep'
      summary: Все справочники.
      tags:
      - dic
  /profile:
    get:
      operationId: hProfileGet
      responses:
        "200":
          $ref: '#/responses/profileRep'
        "400":
          $ref: '#/responses/errRep'
      security:
      - token: []
      summary: Объект профиля.
      tags:
      - profile
    put:
      operationId: hProfileUpdate
      parameters:
      - description: '`type_id` и `phone` игнорируется'
        in: body
        name: Body
        schema:
          $ref: '#/definitions/UsrCUSt'
      responses:
        "200":
          description: ""
        "400":
          $ref: '#/responses/errRep'
      security:
      - token: []
      summary: Изменить данные профиля.
      tags:
      - profile
  /profile/auth:
    post:
      operationId: hProfileAuth
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/PhoneAndSmsCodeSt'
      responses:
        "200":
          $ref: '#/responses/profileAuthRep'
        "400":
          $ref: '#/responses/errRep'
      summary: Авторизация.
      tags:
      - profile
  /profile/change_phone:
    put:
      operationId: hProfileChangePhone
      parameters:
      - description: |-
          `phone` - это новый номер
          <br/>`sms_code` должен быть отправлен на новый номер
        in: body
        name: Body
        schema:
          $ref: '#/definitions/PhoneAndSmsCodeSt'
      responses:
        "200":
          description: ""
        "400":
          $ref: '#/responses/errRep'
      security:
      - token: []
      summary: Изменить основной номер.
      tags:
      - profile
  /profile/id:
    get:
      description: В основном используется для интеграции с другими сервисами в бэкенде
      operationId: hProfileGetId
      responses:
        "200":
          $ref: '#/responses/profileIdRep'
        "400":
          $ref: '#/responses/errRep'
      security:
      - token: []
      summary: Id профиля.
      tags:
      - profile
  /profile/logout:
    post:
      operationId: hProfileLogout
      responses:
        "200":
          description: ""
        "400":
          $ref: '#/responses/errRep'
      security:
      - token: []
      summary: Разлогиниться.
      tags:
      - profile
  /profile/numbers:
    get:
      description: Используется чтоб показать на фронте сколько уведомлении клиент
        пропустил
      operationId: hProfileGetNumbers
      responses:
        "200":
          $ref: '#/responses/profileNumbersRep'
        "400":
          $ref: '#/responses/errRep'
      security:
      - token: []
      summary: Новые цифры профиля (badge).
      tags:
      - profile
  /profile/reg:
    post:
      operationId: hProfileReg
      parameters:
      - description: '`type_id` игнорируется'
        in: body
        name: Body
        schema:
          $ref: '#/definitions/UsrRegReqSt'
      responses:
        "200":
          $ref: '#/responses/profileRegRep'
        "400":
          $ref: '#/responses/errRep'
      summary: Регистрация.
      tags:
      - profile
  /profile/send_validating_code:
    post:
      operationId: hProfileSendPhoneValidatingCode
      parameters:
      - description: '`err_ne` если передать **true** - то вернет в ответе ошибку
          если номера нет в базе'
        in: body
        name: Body
        schema:
          properties:
            err_ne:
              type: boolean
              x-go-name: ErrNE
            phone:
              type: string
              x-go-name: Phone
          type: object
      responses:
        "200":
          description: ""
        "400":
          $ref: '#/responses/errRep'
      summary: Отправить СМС код на номер.
      tags:
      - profile
  /usrs:
    get:
      description: 'Allowed to: `UsrTypeAdmin`'
      operationId: hUsrList
      parameters:
      - format: int64
        in: query
        name: page
        type: integer
        x-go-name: Offset
      - format: int64
        in: query
        name: page_size
        type: integer
        x-go-name: Limit
      - format: int64
        in: query
        name: type_id
        type: integer
        x-go-name: TypeId
      - format: int64
        in: query
        name: only_count
        type: integer
        x-go-name: OnlyCount
      - format: int64
        in: query
        name: search
        type: integer
        x-go-name: Search
      responses:
        "200":
          $ref: '#/responses/usrListRep'
        "400":
          $ref: '#/responses/errRep'
      security:
      - token: []
      tags:
      - usrs
    post:
      description: 'Allowed to: `UsrTypeAdmin`'
      operationId: hUsrCreate
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/UsrCUSt'
      responses:
        "200":
          $ref: '#/responses/usrCreateRep'
        "400":
          $ref: '#/responses/errRep'
      security:
      - token: []
      tags:
      - usrs
  /usrs/{id}:
    delete:
      description: 'Allowed to: `UsrTypeAdmin`'
      operationId: hUsrDelete
      parameters:
      - format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: Id
      responses:
        "200":
          description: ""
        "400":
          $ref: '#/responses/errRep'
      security:
      - token: []
      tags:
      - usrs
    get:
      operationId: hUsrGet
      parameters:
      - format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: Id
      responses:
        "200":
          $ref: '#/responses/usrRep'
        "400":
          $ref: '#/responses/errRep'
      security:
      - token: []
      tags:
      - usrs
    put:
      description: 'Allowed to: `UsrTypeAdmin`'
      operationId: hUsrUpdate
      parameters:
      - format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: Id
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/UsrCUSt'
      responses:
        "200":
          description: ""
        "400":
          $ref: '#/responses/errRep'
      security:
      - token: []
      tags:
      - usrs
produces:
- application/json
responses:
  dicRep:
    description: |-
      `hs` - фронту нужно сохранить значение этого поля и передать в параметре следующего запроса
      <br/>`data` - может быть null, если __hs__ переданный в запросе совпадает с серверным __hs__, в этом случае фронт должен использовать предыдущее значение ответа от сервера
    schema:
      properties:
        data:
          $ref: '#/definitions/DicDataSt'
        hs:
          type: string
          x-go-name: Hs
      type: object
  errRep:
    description: ""
    schema:
      $ref: '#/definitions/ErrRepSt'
  profileAuthRep:
    description: ""
    schema:
      properties:
        id:
          format: int64
          type: integer
          x-go-name: Id
        token:
          type: string
          x-go-name: Token
      type: object
  profileIdRep:
    description: ""
    schema:
      properties:
        id:
          format: int64
          type: integer
          x-go-name: Id
      type: object
  profileNumbersRep:
    description: ""
    schema:
      $ref: '#/definitions/UsrNumbersSt'
  profileRegRep:
    description: ""
    schema:
      properties:
        id:
          format: int64
          type: integer
          x-go-name: Id
        token:
          type: string
          x-go-name: Token
      type: object
  profileRep:
    description: ""
    schema:
      $ref: '#/definitions/UsrProfileSt'
  usrCreateRep:
    description: ""
    schema:
      properties:
        id:
          format: int64
          type: integer
          x-go-name: Id
      type: object
  usrListRep:
    description: ""
    schema:
      properties:
        page:
          format: int64
          type: integer
          x-go-name: Page
        page_size:
          format: int64
          type: integer
          x-go-name: PageSize
        results:
          items:
            $ref: '#/definitions/UsrListSt'
          type: array
          x-go-name: Results
        total_count:
          format: int64
          type: integer
          x-go-name: TotalCount
      type: object
  usrRep:
    description: ""
    schema:
      $ref: '#/definitions/UsrSt'
schemes:
- https
- http
securityDefinitions:
  token:
    description: 'Пример: `Authorization: 2cf24dba5fb0a30e26e83b2`'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
